---
- name: mount disk 
  hosts: kube-node
  remote_user: yqg
  gather_facts: no
  tasks:
    - name: file -s /dev/xvdb
      shell: file -s /dev/xvdb
      become: true
      become_user: root

    - name: mkdir /data
      file: 
        path: /data
        state: directory
        owner: yqg
        group: yqg
      become: true
      become_user: root

    - name: mkfs -t ext4 /dev/xvdb
      shell: mkfs -t ext4 /dev/xvdb
      become: true
      become_user: root

    - name: mount /dev/xvdb /data
      shell: mount /dev/xvdb /data
      become: true
      become_user: root

    - name: echo '\n/dev/xvdb /data ext4 defaults 0 0' >> /etc/fstab
      shell: echo '\n/dev/xvdb /data ext4 defaults 0 0' >> /etc/fstab
      become: true
      become_user: root
      

